# Generated by Django 5.2.6 on 2025-09-17 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_users', '0002_alter_doctorprofile_user_alter_patientprofile_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctorprofile',
            name='hospital',
        ),
        migrations.RemoveField(
            model_name='doctorprofile',
            name='rate',
        ),
        migrations.RemoveField(
            model_name='doctorprofile',
            name='years_of_experience',
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='consultation_fee',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=7),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='major',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='major_description',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='phone_number',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='work_end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='work_start_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='doctorprofile',
            name='profile_image',
            field=models.ImageField(blank=True, default='doctors/doctor.jpeg', null=True, upload_to='doctors/'),
        ),
        migrations.AlterField(
            model_name='patientprofile',
            name='profile_image',
            field=models.ImageField(blank=True, default='patients/patient.jpeg', null=True, upload_to='patients/'),
        ),
    ]
