# Generated by Django 5.2.6 on 2025-09-17 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_users', '0003_remove_doctorprofile_hospital_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorprofile',
            name='consultation_fee',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
        ),
    ]
