# Generated by Django 5.2.6 on 2025-09-18 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_users', '0004_alter_doctorprofile_consultation_fee'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorprofile',
            name='location_medical_office',
            field=models.TextField(blank=True, max_length=400, null=True),
        ),
    ]
