# Generated by Django 5.2.6 on 2025-09-18 08:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profile_users', '0005_doctorprofile_location_medical_office'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_approved', models.BooleanField(default=False)),
                ('appointment', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=60)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profile_users.doctorprofile')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profile_users.patientprofile')),
            ],
        ),
    ]
