# Generated by Django 5.2.6 on 2025-09-26 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='created_at',
            field=models.DateField(auto_now_add=True),
            preserve_default=False,
        ),
    ]
