# Generated by Django 5.2.6 on 2025-09-27 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_account', '0004_remove_user_username_alter_user_email'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
    ]
